-- RDS PostgreSQL 16.14의 public 스키마 기준 (2026-09-16 추출).
-- 기존 RDS는 스키마 확인 후 baseline 1을 등록하며, 빈 DB에서만 이 SQL을 실행한다.
-- 기존 테이블 정리는 후속 마이그레이션에서 처리한다.
-- public 스키마는 PostgreSQL/Flyway가 준비하므로 여기서 생성하지 않는다.

CREATE TABLE public.champion_item_rollup (
    id bigint NOT NULL,
    champion_game_count_all integer NOT NULL,
    champion_game_count_recent integer NOT NULL,
    champion_id integer NOT NULL,
    item_id bigint NOT NULL,
    purchase_count_all integer NOT NULL,
    purchase_count_recent integer NOT NULL,
    win_count_all integer NOT NULL,
    win_count_recent integer NOT NULL
);

ALTER TABLE public.champion_item_rollup ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.champion_item_rollup_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.champion_item_stats (
    id bigint NOT NULL,
    champion_game_count_all integer NOT NULL,
    champion_game_count_recent integer NOT NULL,
    champion_id integer NOT NULL,
    item_id bigint NOT NULL,
    "position" character varying(16) NOT NULL,
    purchase_count_all integer NOT NULL,
    purchase_count_recent integer NOT NULL,
    win_count_all integer NOT NULL,
    win_count_recent integer NOT NULL,
    champion_win_count_all integer DEFAULT 0 NOT NULL,
    CONSTRAINT champion_item_stats_position_check CHECK ((("position")::text = ANY ((ARRAY['TOP'::character varying, 'JUNGLE'::character varying, 'MID'::character varying, 'BOTTOM'::character varying, 'SUPPORT'::character varying])::text[])))
);

ALTER TABLE public.champion_item_stats ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.champion_item_stats_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.champion_pair_item_stats (
    id bigint NOT NULL,
    co_count_all integer NOT NULL,
    co_count_recent integer NOT NULL,
    item_id bigint NOT NULL,
    my_champion_id integer NOT NULL,
    other_champion_id integer NOT NULL,
    pair_game_count_all integer NOT NULL,
    pair_game_count_recent integer NOT NULL,
    relation character varying(8) NOT NULL,
    win_count_all integer NOT NULL,
    win_count_recent integer NOT NULL,
    pair_win_count_all integer DEFAULT 0 NOT NULL,
    CONSTRAINT champion_pair_item_stats_relation_check CHECK (((relation)::text = ANY ((ARRAY['ALLY'::character varying, 'ENEMY'::character varying])::text[])))
);

ALTER TABLE public.champion_pair_item_stats ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.champion_pair_item_stats_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.champion_tags (
    champion_id bigint NOT NULL,
    tag character varying(255),
    CONSTRAINT champion_tags_tag_check CHECK (((tag)::text = ANY ((ARRAY['TANK'::character varying, 'FIGHTER'::character varying, 'MAGE'::character varying, 'ASSASSIN'::character varying, 'MARKSMAN'::character varying, 'SUPPORT'::character varying])::text[])))
);

CREATE TABLE public.champions (
    champion_id bigint NOT NULL,
    name character varying(255) NOT NULL,
    riot_key character varying(255) NOT NULL
);

CREATE TABLE public.composition_stats (
    id bigint NOT NULL,
    ally_has_marksman boolean,
    ally_tank_heavy boolean,
    build_key character varying(512) NOT NULL,
    "position" character varying(255) NOT NULL,
    enemy_ap_heavy boolean,
    enemy_assassin_heavy boolean,
    enemy_tank_heavy boolean,
    game_count integer,
    patch character varying(16) NOT NULL,
    queue_id integer NOT NULL,
    stats_key character varying(1024) NOT NULL,
    tier character varying(32),
    win_count integer,
    champion_id bigint NOT NULL,
    CONSTRAINT composition_stats_position_check CHECK ((("position")::text = ANY ((ARRAY['TOP'::character varying, 'JUNGLE'::character varying, 'MID'::character varying, 'BOTTOM'::character varying, 'SUPPORT'::character varying])::text[])))
);

ALTER TABLE public.composition_stats ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.composition_stats_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.composition_stats_items (
    composition_stats_id bigint NOT NULL,
    item_id bigint NOT NULL,
    item_order integer NOT NULL,
    CONSTRAINT composition_stats_items_item_order_check CHECK ((item_order >= 0))
);

CREATE TABLE public.composition_stats_samples (
    id bigint NOT NULL,
    match_id character varying(32) NOT NULL,
    puuid character varying(128) NOT NULL,
    win boolean,
    composition_stats_id bigint NOT NULL
);

ALTER TABLE public.composition_stats_samples ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.composition_stats_samples_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.embeddings (
    embedding_id bigint NOT NULL,
    algorithm_version character varying(32) NOT NULL,
    entity_id bigint NOT NULL,
    entity_type character varying(16) NOT NULL,
    trained_at timestamp(6) without time zone NOT NULL,
    vector text NOT NULL,
    CONSTRAINT embeddings_entity_type_check CHECK (((entity_type)::text = ANY ((ARRAY['CHAMPION'::character varying, 'ITEM'::character varying])::text[])))
);

ALTER TABLE public.embeddings ALTER COLUMN embedding_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.embeddings_embedding_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.feedback (
    feedback_id bigint NOT NULL,
    content character varying(255),
    date date
);

ALTER TABLE public.feedback ALTER COLUMN feedback_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.feedback_feedback_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.item_meta_stats (
    id bigint NOT NULL,
    item_id bigint NOT NULL,
    patch character varying(16) NOT NULL,
    pick_count integer NOT NULL,
    "position" character varying(16) NOT NULL,
    scope_game_count integer NOT NULL,
    win_count integer NOT NULL,
    CONSTRAINT item_meta_stats_position_check CHECK ((("position")::text = ANY ((ARRAY['TOP'::character varying, 'JUNGLE'::character varying, 'MID'::character varying, 'BOTTOM'::character varying, 'SUPPORT'::character varying])::text[])))
);

ALTER TABLE public.item_meta_stats ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.item_meta_stats_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.item_tags (
    item_id bigint NOT NULL,
    tag character varying(255)
);

CREATE TABLE public.items (
    item_id bigint NOT NULL,
    name character varying(255) NOT NULL,
    tags jsonb DEFAULT '[]'::jsonb NOT NULL
);

CREATE TABLE public.match_participant_cohorts (
    id bigint NOT NULL,
    collected_at timestamp(6) with time zone NOT NULL,
    division character varying(4) NOT NULL,
    match_id character varying(32) NOT NULL,
    puuid character varying(128) NOT NULL,
    queue_type character varying(32) NOT NULL,
    tier character varying(32) NOT NULL
);

ALTER TABLE public.match_participant_cohorts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.match_participant_cohorts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.mined_sequential_patterns (
    pattern_id bigint NOT NULL,
    algorithm_version character varying(32) NOT NULL,
    champion_id bigint NOT NULL,
    items text NOT NULL,
    patch character varying(16) NOT NULL,
    pattern_key character varying(512) NOT NULL,
    "position" character varying(16) NOT NULL,
    scope_total_count integer NOT NULL,
    support_count integer NOT NULL,
    tier character varying(32),
    win_count integer NOT NULL,
    CONSTRAINT mined_sequential_patterns_position_check CHECK ((("position")::text = ANY ((ARRAY['TOP'::character varying, 'JUNGLE'::character varying, 'MID'::character varying, 'BOTTOM'::character varying, 'SUPPORT'::character varying])::text[])))
);

ALTER TABLE public.mined_sequential_patterns ALTER COLUMN pattern_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mined_sequential_patterns_pattern_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.normalized_match_participants (
    id bigint NOT NULL,
    champion_id integer NOT NULL,
    core_item_purchase_order text NOT NULL,
    core_item_purchase_order_complete boolean NOT NULL,
    final_core_item_ids text NOT NULL,
    match_id character varying(32) NOT NULL,
    participant_id integer NOT NULL,
    patch character varying(16) NOT NULL,
    "position" character varying(32),
    puuid character varying(128) NOT NULL,
    queue_id integer NOT NULL,
    team_id integer NOT NULL,
    win boolean NOT NULL,
    tier character varying(32)
);

ALTER TABLE public.normalized_match_participants ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.normalized_match_participants_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.player_cohorts (
    id bigint NOT NULL,
    collected_at timestamp(6) with time zone NOT NULL,
    division character varying(4) NOT NULL,
    puuid character varying(128) NOT NULL,
    queue_type character varying(32) NOT NULL,
    tier character varying(32) NOT NULL
);

ALTER TABLE public.player_cohorts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.player_cohorts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.players (
    puuid character varying(128) NOT NULL,
    first_seen_at timestamp(6) with time zone NOT NULL,
    last_seen_at timestamp(6) with time zone NOT NULL,
    platform character varying(16) NOT NULL,
    division character varying(4),
    tier character varying(32)
);

CREATE TABLE public.quarantined_raw_matches (
    match_id character varying(32),
    raw_data text
);

CREATE TABLE public.raw_match_timelines (
    match_id character varying(32) NOT NULL,
    raw_data text NOT NULL
);

CREATE TABLE public.raw_matches (
    match_id character varying(32) NOT NULL,
    raw_data text NOT NULL
);

CREATE TABLE public.stats_aggregation_completions (
    id bigint NOT NULL,
    aggregation_revision character varying(16) NOT NULL,
    completed_at timestamp(6) with time zone NOT NULL,
    match_id character varying(32) NOT NULL,
    puuid character varying(128) NOT NULL,
    queue_type character varying(32) NOT NULL,
    tier character varying(32) NOT NULL
);

ALTER TABLE public.stats_aggregation_completions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stats_aggregation_completions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.champion_item_rollup
    ADD CONSTRAINT champion_item_rollup_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.champion_item_stats
    ADD CONSTRAINT champion_item_stats_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.champion_pair_item_stats
    ADD CONSTRAINT champion_pair_item_stats_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.champions
    ADD CONSTRAINT champions_pkey PRIMARY KEY (champion_id);

ALTER TABLE ONLY public.composition_stats_items
    ADD CONSTRAINT composition_stats_items_pkey PRIMARY KEY (composition_stats_id, item_order);

ALTER TABLE ONLY public.composition_stats
    ADD CONSTRAINT composition_stats_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.composition_stats_samples
    ADD CONSTRAINT composition_stats_samples_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.embeddings
    ADD CONSTRAINT embeddings_pkey PRIMARY KEY (embedding_id);

ALTER TABLE ONLY public.feedback
    ADD CONSTRAINT feedback_pkey PRIMARY KEY (feedback_id);

ALTER TABLE ONLY public.item_meta_stats
    ADD CONSTRAINT item_meta_stats_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.items
    ADD CONSTRAINT items_pkey PRIMARY KEY (item_id);

ALTER TABLE ONLY public.match_participant_cohorts
    ADD CONSTRAINT match_participant_cohorts_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.mined_sequential_patterns
    ADD CONSTRAINT mined_sequential_patterns_pkey PRIMARY KEY (pattern_id);

ALTER TABLE ONLY public.normalized_match_participants
    ADD CONSTRAINT normalized_match_participants_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.player_cohorts
    ADD CONSTRAINT player_cohorts_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.players
    ADD CONSTRAINT players_pkey PRIMARY KEY (puuid);

ALTER TABLE ONLY public.raw_match_timelines
    ADD CONSTRAINT raw_match_timelines_pkey PRIMARY KEY (match_id);

ALTER TABLE ONLY public.raw_matches
    ADD CONSTRAINT raw_matches_pkey PRIMARY KEY (match_id);

ALTER TABLE ONLY public.stats_aggregation_completions
    ADD CONSTRAINT stats_aggregation_completions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.champion_item_rollup
    ADD CONSTRAINT uk_champion_item_rollup UNIQUE (champion_id, item_id);

ALTER TABLE ONLY public.champion_item_stats
    ADD CONSTRAINT uk_champion_item_stats UNIQUE (champion_id, "position", item_id);

ALTER TABLE ONLY public.champion_pair_item_stats
    ADD CONSTRAINT uk_champion_pair_item_stats UNIQUE (my_champion_id, other_champion_id, relation, item_id);

ALTER TABLE ONLY public.composition_stats_samples
    ADD CONSTRAINT uk_composition_stats_sample UNIQUE (composition_stats_id, match_id, puuid);

ALTER TABLE ONLY public.embeddings
    ADD CONSTRAINT uk_embeddings_entity_algorithm UNIQUE (entity_type, entity_id, algorithm_version);

ALTER TABLE ONLY public.item_meta_stats
    ADD CONSTRAINT uk_item_meta_stats UNIQUE (patch, "position", item_id);

ALTER TABLE ONLY public.match_participant_cohorts
    ADD CONSTRAINT uk_match_participant_cohort UNIQUE (match_id, puuid, queue_type);

ALTER TABLE ONLY public.normalized_match_participants
    ADD CONSTRAINT uk_normalized_match_participant UNIQUE (match_id, puuid);

ALTER TABLE ONLY public.player_cohorts
    ADD CONSTRAINT uk_player_cohort UNIQUE (puuid, queue_type);

ALTER TABLE ONLY public.stats_aggregation_completions
    ADD CONSTRAINT uk_stats_aggregation_completion_target UNIQUE (match_id, puuid, queue_type, tier, aggregation_revision);

ALTER TABLE ONLY public.champions
    ADD CONSTRAINT ukmlub6kmf9q7igidrni71ql4pv UNIQUE (riot_key);

ALTER TABLE ONLY public.composition_stats
    ADD CONSTRAINT ukt75j38i0vh0kv4pjufe9yqq34 UNIQUE (stats_key);

CREATE INDEX idx_cis_champion_position ON public.champion_item_stats USING btree (champion_id, "position");

CREATE INDEX idx_cpis_lookup ON public.champion_pair_item_stats USING btree (my_champion_id, relation, other_champion_id);

CREATE INDEX idx_ims_position_item ON public.item_meta_stats USING btree ("position", item_id);

CREATE INDEX idx_match_participant_cohort_stats_pending ON public.match_participant_cohorts USING btree (queue_type, tier, match_id, puuid);

CREATE INDEX idx_nmp_champion_position_patch ON public.normalized_match_participants USING btree (champion_id, "position", patch);

CREATE INDEX idx_stats_aggregation_completion_lookup ON public.stats_aggregation_completions USING btree (queue_type, tier, aggregation_revision, match_id, puuid);

ALTER TABLE ONLY public.composition_stats_items
    ADD CONSTRAINT fk1qcyrdtwf1rs0c14o5jp84414 FOREIGN KEY (item_id) REFERENCES public.items(item_id);

ALTER TABLE ONLY public.composition_stats_samples
    ADD CONSTRAINT fkaucpeq17akascdloxt2su9q7j FOREIGN KEY (composition_stats_id) REFERENCES public.composition_stats(id);

ALTER TABLE ONLY public.composition_stats_items
    ADD CONSTRAINT fkgvcl825rm9scno8pld3flkfd6 FOREIGN KEY (composition_stats_id) REFERENCES public.composition_stats(id);

ALTER TABLE ONLY public.champion_tags
    ADD CONSTRAINT fkgyip0sthtoctu0xqvamuk2y0s FOREIGN KEY (champion_id) REFERENCES public.champions(champion_id);

ALTER TABLE ONLY public.item_tags
    ADD CONSTRAINT fkjv1mnuei30kq5rly4y4e7wv5t FOREIGN KEY (item_id) REFERENCES public.items(item_id);

ALTER TABLE ONLY public.composition_stats
    ADD CONSTRAINT fkpnjfntrmfdrbkh6i7k1612oim FOREIGN KEY (champion_id) REFERENCES public.champions(champion_id);
