-- 기존 참가자/Core 테이블은 유지하고 전체 아이템의 구매만 별도로 저장한다.
CREATE TABLE normalized_match_participant_item_purchases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id VARCHAR(32) NOT NULL,
    participant_id INTEGER NOT NULL CHECK (participant_id > 0),
    -- Core뿐 아니라 시작·재료·신발·소모품을 포함한 참가자별 전체 구매 순서.
    -- 취소된 구매도 순번은 보존한다. 학습 제외와 인벤토리 복원은 Raw 이벤트로 별도 처리한다.
    purchase_order INTEGER NOT NULL CHECK (purchase_order > 0),
    item_id INTEGER NOT NULL CHECK (item_id > 0),
    -- 원천 행동(ITEM_PURCHASED)이 아니라 서비스의 아이템 분류다.
    purchase_type VARCHAR(32) NOT NULL CHECK (
        purchase_type IN ('STARTER', 'COMPONENT', 'CORE', 'BOOTS', 'CONSUMABLE', 'OTHER')
    ),
    game_time_ms INTEGER CHECK (game_time_ms >= 0),
    -- 구매 직전 골드 및 실제 추가 지불액. 미확보 값은 0 대신 NULL을 유지한다.
    -- 프레임 골드나 미검증 추정값을 구매 직전 관측값으로 저장하지 않는다.
    current_gold INTEGER CHECK (current_gold >= 0),
    item_cost INTEGER CHECK (item_cost >= 0),
    patch VARCHAR(16) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_participant_item_purchase UNIQUE (match_id, participant_id, purchase_order)
);
