CREATE USER dfgg WITH PASSWORD 'dfgg';
CREATE DATABASE dfgg;
GRANT ALL PRIVILEGES ON DATABASE dfgg TO dfgg;
ALTER DATABASE dfgg OWNER TO dfgg;

CREATE DATABASE dfgg_test;
GRANT ALL PRIVILEGES ON DATABASE dfgg_test TO dfgg;
ALTER DATABASE dfgg_test OWNER TO dfgg;