# dfgg 지표 수집.
global:
  scrape_interval: 30s
  scrape_timeout: 10s
  external_labels:
    monitor: dfgg

scrape_configs:
  - job_name: dfgg-app
    metrics_path: /blue
    static_configs:
      - targets: [ "10.0.0.221:9090" ]
        labels: { env: prod, slot: blue }
      - targets: [ "10.0.0.114:9090" ]
        labels: { env: dev, slot: blue }

  - job_name: dfgg-app-green
    metrics_path: /green
    static_configs:
      - targets: [ "10.0.0.221:9090" ]
        labels: { env: prod, slot: green }
      - targets: [ "10.0.0.114:9090" ]
        labels: { env: dev, slot: green }

  - job_name: dfgg-node
    metrics_path: /node
    static_configs:
      - targets: [ "10.0.0.221:9090" ]
        labels: { env: prod }
      - targets: [ "10.0.0.114:9090" ]
        labels: { env: dev }

  - job_name: dfgg-monitoring
    static_configs:
      - targets: [ "127.0.0.1:9100" ]
        labels: { env: monitoring }

  - job_name: prometheus
    static_configs:
      - targets: [ "127.0.0.1:9090" ]
