name: BE CD - EC2(BE/Dev)

on:
  push:
    branches: [ "BE/dev" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./backend/dfgg

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Copy .env file
        run: cp /home/ubuntu/app-config/.env ./.env

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup and Build with Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          build-root-directory: ./backend/dfgg
          arguments: clean build --no-daemon -x test

      - name: Restart service
        run: sudo systemctl restart dfgg-be.service

      - name: Check service status
        run: |
          sleep 3
          sudo systemctl status dfgg.service --no-pager
